# SPDX-FileCopyrightText: Copyright (c) <2025> NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
import enum
from typing import Any, Sequence, TypeAlias

from cuda.tile._context import TileContextConfig
from cuda.tile._memory_model import MemorySpace

Dim3: TypeAlias = tuple[int] | tuple[int, int] | tuple[int, int, int]


class DType:
    """A *data type* (or *dtype*) describes the type of the objects of an |array|, |tile|, or
    operation.

    |Dtypes| determine how values are stored in memory and how operations on those values are
    performed.
    """

    @property
    def bitwidth(self):
        """The number of bits in an element of the |data type|."""

    @property
    def name(self):
        """The name of the |data type|."""

    def __call__(self, value, /):
        """Construct a Scalar of this |data type| from a value."""


def is_numeric(t: DType, /) -> bool: ...
def is_boolean(t: DType, /) -> bool: ...
def is_integral(t: DType, /) -> bool: ...
def is_signed(t: DType, /) -> bool: ...
def is_float(t: DType, /) -> bool: ...
def is_unrestricted_float(t: DType, /) -> bool: ...
def is_restricted_float(t: DType, /) -> bool: ...
def is_arithmetic(t: DType, /) -> bool: ...
def _is_pointer_dtype(t: DType, /) -> bool: ...
def _is_foreign_pointer_dtype(t: DType, /) -> bool: ...

def _get_pointer_dtype(pointee_dtype: DType | None, memory_space: MemorySpace, /) -> DType: ...
def _get_foreign_pointer_dtype(pointee_dtype: DType, /) -> DType: ...
def _pointer_pointee_dtype(pointer_dtype: DType, /) -> DType: ...
def _pointer_memory_space(pointer_dtype: DType, /) -> MemorySpace: ...
def _foreign_pointer_pointee_dtype(foreign_pointer_dtype: DType, /) -> DType: ...

def integer_dtype_min(dtype: DType) -> int: ...
def integer_dtype_max(dtype: DType) -> int: ...


bool_: DType
uint8: DType
uint16: DType
uint32: DType
uint64: DType
int8: DType
int16: DType
int32: DType
int64: DType
float16: DType
float32: DType
float64: DType
bfloat16: DType
tfloat32: DType
float8_e4m3fn: DType
float8_e5m2: DType
float8_e8m0fnu: DType
float8_e5m3fnu: DType
float4_e2m1fn: DType
mbarrier: DType
cluster_launch_control_token: DType
tensor_map_descriptor: DType
float6_e2m3fn: DType
float6_e3m2fn: DType


def launch(stream,
           grid: Dim3,
           kernel,
           kernel_args: tuple[Any, ...],
           /, *,
           programmatic_dependent_launch: bool = False):
    ...


def launch_extended(stream,
                    block_count: Dim3,
                    thread_count: Dim3,
                    kernel,
                    kernel_args: tuple[Any, ...],
                    /, *,
                    cooperative: bool = False,
                    block_in_cluster_count: Dim3 | None = None,
                    preferred_block_in_cluster_count: Dim3 | None = None,
                    programmatic_dependent_launch: bool = False
                    ):
    ...


def get_compute_capability(device_id: int = 0) -> tuple[int, int]:
    ...


def get_driver_version():
    ...


def _get_max_grid_size(device_id, /):
    ...


def get_parameter_constraints_from_pyargs(dispatcher, pyargs, calling_convention, /):
    ...


class ConstantKind(enum.Enum):
    ...


def classify_constant(value, kernel_arg, /) -> ConstantKind | None:
    ...


def foreign_dtype_object_register(foreign, native):
    ...


def foreign_dtype_object_to_native(foreign, /):
    ...


def dev_features_enabled():
    ...


def cconv_v3_enabled():
    ...


class TileDispatcher:
    def __init__(self, parameter_annotations: Sequence):
        ...


class HostDispatcher:
    def __init__(self, parameter_annotations: Sequence):
        ...


class TileContext:
    def __init__(self, config: TileContextConfig):
        ...

    @property
    def config(self) -> TileContextConfig:
        ...

    @property
    def autotune_cache(self) -> Any | None:
        ...

    @autotune_cache.setter
    def autotune_cache(self, value: Any | None):
        ...


class CallingConvention:
    @staticmethod
    def cutile_python_v1() -> "CallingConvention":
        ...

    @staticmethod
    def cutile_python_v2() -> "CallingConvention":
        ...

    @staticmethod
    def from_code(code: str, /) -> "CallingConvention":
        ...

    @property
    def name(self) -> str:
        ...

    @property
    def code(self) -> str:
        ...

    @property
    def version(self) -> int:
        ...


default_tile_context: TileContext


def _synchronize_context() -> None: ...
def _create_stream() -> int: ...
def _destroy_stream(stream: int) -> None: ...
def _benchmark(stream: int,
               grid: tuple[int] | tuple[int, int] | tuple[int, int, int],
               kernel,
               pyargs_tuples: tuple[tuple[Any, ...], ...],
               flush_l2: bool = True,
               /) -> float: ...


def run_coroutine(coro):
    """
    Run a coroutine using a software stack to bypass the Python's recursion limit.
    Use resume_after() to break the call chain and push a new frame to the software stack.
    """


def _export_ipc_benchmark_payload(stream: int,
                                  grid: tuple[int] | tuple[int, int] | tuple[int, int, int],
                                  kernel,
                                  pyargs_tuples: tuple[Any, ...],
                                  flush_l2: bool = True,
                                  /) -> bytes | None: ...


def _benchmark_with_ipc_payload(payload: bytes, /) -> float: ...


class TensorMapDataType(enum.Enum):
    UINT8 = ...
    UINT16 = ...
    UINT32 = ...
    INT32 = ...
    UINT64 = ...
    INT64 = ...
    FLOAT16 = ...
    FLOAT32 = ...
    FLOAT64 = ...
    BFLOAT16 = ...
    FLOAT32_FTZ = ...
    TFLOAT32 = ...
    TFLOAT32_FTZ = ...
    _16U4_ALIGN8B = ...
    _16U4_ALIGN16B = ...
    _16U6_ALIGN16B = ...


class TensorMapInterleave(enum.Enum):
    NONE = ...
    INTERLEAVE_16B = ...
    INTERLEAVE_32B = ...


class SwizzleMode(enum.Enum):
    SWIZZLE_NONE = ...
    SWIZZLE_32B = ...
    SWIZZLE_64B = ...
    SWIZZLE_128B = ...
    SWIZZLE_128B_ATOM_32B = ...
    SWIZZLE_128B_ATOM_32B_FLIP_8B = ...
    SWIZZLE_128B_ATOM_64B = ...


class TensorMapL2Promotion(enum.Enum):
    NONE = ...
    L2_64B = ...
    L2_128B = ...
    L2_256B = ...


class TensorMapFloatOOBFill(enum.Enum):
    NONE = ...
    NAN_REQUEST_ZERO_FMA = ...


class TMALoadMode(enum.Enum):
    TILE = ...
    IM2COL = ...
    IM2COL_W = ...
    IM2COL_W_128 = ...
    TILE_GATHER4 = ...


class TMAStoreMode(enum.Enum):
    TILE = ...
    IM2COL = ...
    TILE_SCATTER4 = ...


_TENSOR_MAP_DESCRIPTOR_BYTES: int
_TENSOR_MAP_DESCRIPTOR_ALIGNMENT: int
_TENSOR_MAP_MAX_RANK: int


def _tensor_map_data_type_bitwidth(data_type: int, /) -> int: ...


def _tensor_map_tiled(
    array: Any,
    tile_shape: tuple[int, ...],
    order: tuple[int, ...],
    interleave: int,
    swizzle: int,
    l2_promotion: int,
    oob_fill: int,
    /,
) -> bytes: ...


class BitstreamWriter:
    def fixed1(self, value: int) -> None: ...
    def fixed2(self, value: int) -> None: ...
    def fixed3(self, value: int) -> None: ...
    def fixed4(self, value: int) -> None: ...
    def fixed8(self, value: int) -> None: ...
    def fixed32(self, value: int) -> None: ...

    def vbr4(self, value: int) -> None: ...
    def vbr5(self, value: int) -> None: ...
    def vbr6(self, value: int) -> None: ...
    def vbr8(self, value: int) -> None: ...

    def align_to_word(self) -> int: ...
    def aligned_word(self, value: int) -> int: ...
    def patch_word(self, offset: int, value: int) -> None: ...

    def raw_blob(self, data: bytearray) -> None: ...

    def to_bytes(self) -> bytes: ...


class NVVMProgram:
    def add_module(self, contents: bytes | bytearray, name: str, /) -> None: ...
    def compile(self, options: Sequence[str], /) -> bytes: ...


class NVVM:
    def __init__(self, dll_path: str, /): ...
    def ir_version(self) -> tuple[int, int, int, int]: ...
    def version(self) -> tuple[int, int]: ...
    def create_program(self) -> NVVMProgram: ...
